<a href="https://colab.research.google.com/github/sohail-avv-amravati/Machine-learning/blob/main/Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
print("S.Sohail")
print("24319")
print("CSE-B")
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr)
#2.shape of array
shape=arr.shape
print(shape)
max=arr.max()
min=arr.min()
print(arr.mean())
print(arr.std())
reshaped_array=arr.reshape(4,5)
print(max,min)
for i in range (0,4):
    array2=reshaped_array[1]
print(array2)
array3=reshaped_array[:,2]
print(array3)

S.Sohail
24319
CSE-B
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
10.5
5.766281297335398
20 1
[ 6  7  8  9 10]
[ 3  8 13 18]


In [5]:
import numpy as np
print("S.Sohail")
print("24319")
print("CSE-B")
A=np.array([10,20,30,40,50])
B=np.array([5,10,15,20,25])
add=np.add(A,B)
sub=np.subtract(B,A)
mult=np.multiply(A,B)
divid=np.divide(A,B)
sumA=np.sum(A)
print(A)
print(B)
print(add)
print(sub)
print(mult)
print(divid)
print(sumA)

S.Sohail
24319
CSE-B
[10 20 30 40 50]
[ 5 10 15 20 25]
[15 30 45 60 75]
[ -5 -10 -15 -20 -25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
150


In [7]:
import numpy as np
import pandas as pd
print("S.Sohail")
print("24319")
print("CSE-B")
data={"Roll_NO":[101,102,103,104,105],"Name":["Ravi","Priya","Kiran","Anu","Sita"],"Marks":[85,92,78,88,95]}
df=pd.DataFrame(data)
print(df,"\n\n")
print(df.head(3),"\n\n\n")
average = df['Marks'].mean()
print(average)
higest=df.loc[df["Marks"].idxmax(),"Name"]
print("\n\n\n",higest)
lowest=df.loc[df["Marks"].idxmin(),"Name"]
print("\n\n\n",lowest)
conditions=[df["Marks"]>=90 ,df["Marks"]>=80,df["Marks"]<80]
grades=["A","B","C"]
df["Grades"]=np.select(conditions,grades, default="")
print(df)

S.Sohail
24319
CSE-B
   Roll_NO   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
3      104    Anu     88
4      105   Sita     95 


   Roll_NO   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78 



87.6



 Sita



 Kiran
   Roll_NO   Name  Marks Grades
0      101   Ravi     85      B
1      102  Priya     92      A
2      103  Kiran     78      C
3      104    Anu     88      B
4      105   Sita     95      A


In [12]:
import pandas as pd
print("S.Sohail")
print("24319")
print("CSE-B\n")
data = {
    'Product': ['Laptop',"Mouse","Keyboard","Monitor"],
    'Price':[50000,500,1200,10000],
    'Quantity':[10,50,30,15]
}
df=pd.DataFrame(data)
print(df,"\n")
df['Total Value'] = df['Price'] * df['Quantity']
print("1 & 2. Updated DataFrame with 'Total Value':")
print(df,"\n")
highest_val_product = df.loc[df['Total Value'].idxmax(), 'Product']
print(f"3. Product with the highest total value: {highest_val_product}")
overall_value = df['Total Value'].sum()
print(f"\n4. Overall inventory value: Rs. {overall_value:,}")


S.Sohail
24319
CSE-B

    Product  Price  Quantity
0    Laptop  50000        10
1     Mouse    500        50
2  Keyboard   1200        30
3   Monitor  10000        15 

1 & 2. Updated DataFrame with 'Total Value':
    Product  Price  Quantity  Total Value
0    Laptop  50000        10       500000
1     Mouse    500        50        25000
2  Keyboard   1200        30        36000
3   Monitor  10000        15       150000 

3. Product with the highest total value: Laptop

4. Overall inventory value: Rs. 711,000


In [14]:
import pandas as pd
from sklearn.datasets import load_iris
print("S.Sohail")
print("24319")
print("CSE-B\n")
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target
species_map = {i: name for i, name in enumerate(iris.target_names)}
df['species'] = df['species'].map(species_map)
print("\n2. First five records:")
print(df.head())
print("\n" + "="*50 + "\n")
rows, cols = df.shape
print(f"3. Number of Rows: {rows}")
print(f"   Number of Columns: {cols}")
print("\n" + "="*50 + "\n")
print("4. Column names:")
print(list(df.columns))
print("\n" + "="*50 + "\n")
print("5. Missing values per column:")
print(df.isnull().sum())
print("\n" + "="*50 + "\n")
print("6. Summary statistics:")
print(df.describe())
print("\n" + "="*50 + "\n")
print("7. Number of samples per class:")
print(df['species'].value_counts())



S.Sohail
24319
CSE-B


2. First five records:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


3. Number of Rows: 150
   Number of Columns: 5


4. Column names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'species']


5. Missing values per column:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64


6. Summary statistics:
       sepal length (cm)  sepal width (cm)  petal length (cm